### ISSUE TITLE
Yaml Path doesn't exist in file

### ISSUE THREAD

**Issue by Sollembum78** [tim740/skUtilities#11]
I'm using a lot of skquery's yaml reading and writing and everything works fine, but when I install latest skutilities 0.8.8, I get a lot of errors like:

Yaml Path: 'kits.epic.11' doesn't exist in file '/home/desktop/minecraft/res2/kits.yml' (SExprYaml.class)

But clearly exists in specified file and is read properly without skutilities. I tried to disable loadYaml and loadFiles in config of skUtilities but it doesn't help. And since this values can not be read while your plugin is active, I got blank variables, which is a problem. 

What do I do about it? I need skUtilities for GeoIP skript, but this yaml thing is crucial.

Spigot 1.11.2 (latest to date), Skript by Bensku 2.2-dev22f.

**Comment by Syst3ms** [comment]
It's just a warning, shouldn't affect your scripts

If it does, provide more info.

@tim740 Many people have been complaining, so... You may want to fix it.

**Comment by Sollembum78** [comment]
It does affect scripts. I have script that goes like that:
on load:
set {kit::*} to yaml list "kits.items" from file "kits.yml"

command /kit:
(some randomizer and permission checks)
execute console command "give %player% %{kit::%{_randomnumber}%}%"

And if skUtilities is present I get vanilla error, like "there is no item with id < none >", which means skript cannot read my yaml file and set proper values, but if I remove it, everything works fine, variables are properly set to values from kits.yml and proper items are given to players.

Anyway, I found a way to do my geoip thing using just skQuery, without skUtilities, but this addon clearly has some problems.

**Comment by tim740** [comment]
@Sollembum78 
do you have skquery installed as well with skUtilities?
if so that would cause issues

else message me on discord `tim740#1139`

**Comment by Sollembum78** [comment]
Yes, I did have them both installed when got this errors, cause I use skQuery a lot. So they are not compatible? Sad, if so.

**Comment by tim740** [comment]
They are, but it could be using skquery too, which will mess it up, easy fix tho, put `skUtil` in front of my yaml syntaxs

**Comment by tim740** [comment]
If everything works fine please close this issue
