### ISSUE TITLE
"is a file" returning incorrect values

### ISSUE THREAD

**Issue by RezzedUp** [tim740/skUtilities#13]
The "is a file" syntax isn't returning correct values.

* A nonexistent file is a file.
* A directory that clearly exists is not a file.

-----

**Versions:**
* skUtilities version 0.8.9
* Skript version 2.2-dev23 (Bensku)
* CraftBukkit version git-Spigot-b4417b8-a552117 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
* java version "1.8.0_112"

On Windows 10.

-----

Tested with:

```python
on script load:

    #
    #   Checking a file:
    #

    if file "plugins/Skript/scripts/this-does-not-exist.sk" is a file:
    
        #   Returns this:
        send "Wow! It exists somehow." to console
        
    else:
    
        #   Should return this:
        send "It doesn't exist, as expected." to console
    
    #
    #   Checking a directory:
    #
        
    if file "plugins/Skript/" is a file:
    
        #   Should return this:
        send "Correct. Skript does indeed have a directory." to console
        
    else:

        #   Returns this:
        send "Uhh.. this directory exists. Are you crazy?" to console
```
Incorrect results:

![](http://i.imgur.com/CzTKazg.png)

**Comment by tim740** [comment]
Fixed in next version (v0.9.0)
