### ISSUE TITLE
Using different "date format" in skript config breaks the latest "day name" expression

### ISSUE THREAD

**Issue by Portanna** [tim740/skUtilities#14]
## Using a different date format than the default one will result in a console error and a null return

**The date format I used in the skript main config:**

date format: dd.MM.yyyy, HH:mm

**The error I get in console:**

[Server thread/ERROR]: [skUtilities] v0.8.9: Text '17.02.2017, 04:35' could not be parsed at index 2 (ExprDateInner.class)

When changing back the date format in the skript main config to the default one, the expression works as intended.

**Code used** (similar to the default one you wrote on skunity's documentation)**:**

command /datename:
  trigger:
    set {_tmpO} to now
    broadcast "%day name from date {_tmpO}%"

**Comment by tim740** [comment]
`set {_cms} to current system seconds`
then 
`set {_var} to convert unix {_cms} to date formatted as "FORMAT"`
https://www.skunity.com/search?search=unix+to+date+formatted#

**Comment by Portanna** [comment]
My new code:

command /timetest:
__trigger:
_____set {_cms} to current system seconds
_____message "%{_cms}%"
_____set {_tmpO} to convert unix {_cms} to date formatted as "d/M/yyyy h:mm a"
_____message "%{_tmpO}%"
_____message "Date: %{_tmpO}%"
_____message "Year: %year from date {_tmpO}%"
_____message "Month: %month from date {_tmpO}%"
_____message "Month Name: %month name from date {_tmpO}%"
_____message "Day of Year: %day of year from date {_tmpO}%"
_____message "Day of Month: %day of month from date {_tmpO}%"
_____message "Day of Week: %day of week from date {_tmpO}%"
_____message "Day Name: %day name from date {_tmpO}%"
_____message "Hour: %hours from date {_tmpO}%"
_____message "Minute: %minutes from date {_tmpO}%"
_____message "Second: %seconds from date {_tmpO}%"

The outcome:
https://i.gyazo.com/06fc4867d82dae17b2e74a3a94b74473.png

Still can't get this to work. Can you provide me of a direct example?
EDIT: Even using the date format "d/M/yy h:mm a" (which is the system default) does not work.

**Comment by tim740** [comment]
Message me on discord `tim740#1139`

**Comment by Portanna** [comment]
I just sent a friend request, since you do not accept pm from people outside your friend list.

**Comment by Portanna** [comment]
If someone will read this and has the same problem, I solved it this way using Sakamoto's Algorithm:

https://pastebin.com/jCkh7ZpQ

Solved my problem.
