### ISSUE TITLE
Remove error

### ISSUE THREAD

**Issue by McKidPro** [tim740/skUtilities#15]
Code:

> remove "%{_bande}%" from skutil yml list "Bande.Medlem.%loop-value%" of file "plugins/Bande/bander.yml"

Error:

> [22:57:34] [Server thread/ERROR]: #!#! Stack trace:
> [22:57:34] [Server thread/ERROR]: #!#! java.lang.NullPointerException
> [22:57:34] [Server thread/ERROR]: #!#!     at uk.tim740.skUtilities.files.SExprYaml.change(SExprYaml.java:90)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
> [22:57:34] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
> [22:57:34] [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [22:57:34] [Server thread/ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [22:57:34] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [22:57:34] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
> [22:57:34] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
> [22:57:34] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [22:57:34] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [22:57:34] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [22:57:34] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [22:57:34] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
> [22:57:34] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
> [22:57:34] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
> [22:57:34] [Server thread/ERROR]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! Version Information:
> [22:57:34] [Server thread/ERROR]: #!#!   Skript: 2.2-Fixes-V9b
> [22:57:34] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
> [22:57:34] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
> [22:57:34] [Server thread/ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
> [22:57:34] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.19-mod-std-ipv6-64
> [22:57:34] [Server thread/ERROR]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! Running CraftBukkit: false
> [22:57:34] [Server thread/ERROR]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! Current node: null
> [22:57:34] [Server thread/ERROR]: #!#! Current item: remove "%{_bande}(as java.lang.Object)%" from uk.tim740.skUtilities.files.SExprYaml
> [22:57:34] [Server thread/ERROR]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! Thread: Server thread
> [22:57:34] [Server thread/ERROR]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! End of Error.
> [22:57:34] [Server thread/WARN]: #!#! 
> [22:57:34] [Server thread/WARN]: #!#! [Umbaska] List of plugins: 
> [22:57:34] [Server thread/WARN]: #!#! WorldEdit - 6.0.2-SNAPSHOT;3370-58aac973, Skript - 2.2-Fixes-V9b, Essentials - TeamCity, WildSkript - 1.8, EssentialsChat - TeamCity, SQLibrary - 7.1, skUtilities - 0.8.9, SkQuery - 3.5.5-Lime, ViaVersion - 0.9.9, ExtrasSK - 1.1, NametagEdit - 4.1.2, Vault - 1.5.3-b37, EssentialsSpawn - TeamCity, WorldGuard - 6.1.1-SNAPSHOT.1616-c9eaec0, Citizens - 2.0.16-SNAPSHOT (build 1277), PirateSK - 0.4.1, Umbaska - 2.0 Beta 5.5.1, Sentry - 1.8.5, skRayFall - 1.9.2
> [22:57:34] [Server thread/WARN]: #!#! 
> [22:57:34] [Server thread/WARN]: #!#! [Umbaska] List of addons: 
> [22:57:34] [Server thread/WARN]: #!#! PirateSK v0.4.1skUtilities v0.8.9Umbaska v2.0 Beta 5.5.1skRayFall v1.9.2SkQuery v3.5.5-LimeExtrasSK v1.1WildSkript v1.8
> [22:57:34] [Server thread/WARN]: #!#! 
> [22:57:34] [Server thread/ERROR]: #!#! 

Addon Version: 0.8.9 Skript Version: 2.2-Fixes-V9b Minecraft Version: 1.8.8 Java Version: 1.8.0_111

**Comment by tim740** [comment]
Message me on discord `tim740#1139`
