### ISSUE TITLE
Issue with loading files

### ISSUE THREAD

**Issue by ghost** [tim740/skUtilities#17]
Hi,

I'm not sure, if this is an issue made by Skript or SkUtilities, but we're currently switching from an 1.10.2 server to an 1.11.2 server. We are upgrading to the newest Skript build, too.

But when we use our "old" scripts with an external text document in UTF-8 format, the new lines aren't recognized. There is only an "CR"-Logo in a square and the loop does not split it, so there is only one loop-value.

on load: wait 2 seconds $ thread set {tipps::*} to file contents of "plugins/GMiner/GMiner-Tipps.txt"

Skript Version: Dev26c
skUtilities: 9.0

Any idea how to fix it or is it a bug?
https://cloud.githubusercontent.com/assets/23314425/24985239/42c44558-1ff3-11e7-9fdb-b3cb67b7cc9d.png

**Comment by ghost** [comment]
(Tested with Dev25 from Bensku too, doesn't work)

**Comment by tim740** [comment]
Some kind of File Encoding error, make sure it's UTF-8

**Comment by ghost** [comment]
I'm really sure, it is UTF 8 without BOM.
The same file is used on our 1.10.2 server with skUtil 0.7.8 and it works fine.

**Comment by ghost** [comment]
If I use this, it works:
'set {tipps::*} to file contents of "plugins/GMiner/GMiner-Tipps.txt" split at "%nl%" '

**Comment by tim740** [comment]
is this still a issue?

**Comment by ghost** [comment]
Hi,

the issue is still there. We did a little hotfix as described above, so it works.
But that ist not the way, it should be.
In the tab list and simply everywhere when a new line should start the "CR"-Character is there. Is %nl% from Skript or from SkUtil?

**Comment by Snow-Pyon** [comment]
That expression is from skQuery (or Umbaska 3 if you're using it), so it isn't an issue of skUtilities, you can try use the following:
```
last character of new line
```
Someone said that it fixed the issue. Still, not an issue of skUtilities so this should be closed now.
