### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Polymeth** [tim740/skUtilities#18]
- Python or/and Lua integration, e.g: ` invoke python function "sendMessage"`
- Redis integration

**Comment by tutur1004** [comment]
Redis idea:
send effect
​effect: login in to channels ... with "Redis1"
event: on redis message seen by "Redis2":
goal is to have multiple servers listened

**Comment by Snow-Pyon** [comment]
@tutur1004 you should create a new issue for suggest what you want, Skellett and RediSK supports Redid anyways.

**Comment by tutur1004** [comment]
@Snow-Pyon For me, RediSk won't work, I'm logged correctly but send effect or detect event won't work

**Comment by Polymeth** [comment]
Yes, RediSK is broken af

**Comment by tutur1004** [comment]
And the dev' were inactive for more than 5 weeks.. :/

**Comment by Snow-Pyon** [comment]
@tutur1004 Skellett supports it as far I know; and knowing Tim, he'll not add anything that could break in a non-far future.

**Comment by tim740** [comment]
I agree with what @Snow-Pyon Said.
