### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NeusFear** [tim740/skUtilities#19]
Yaml ease of access to lists:
Adding to the current syntax to add a list variable to a yaml list. Currently you have to loop a list and add the values in the loop to the yaml list. Which isn't awful, we can deal with that, but for simplicity's sake. It would be easier to just be able to add a list variable to a yaml list.

**Comment by Syst3ms** [comment]
Well, there will still be a loop anyway, the difference is whether it is in the script or the source code, but yeah.
