### ISSUE TITLE
Addon doesn't load

### ISSUE THREAD

**Issue by Bratatat** [tim740/skUtilities#2]
Dear,

SkUtilities doesn't show up in my plugins list after a reboot on my 1.8.8 (Build 45) spigot server. Here's a list of all my plugins:
_Plugins (24): WorldBorder, PlugMan, VoxelSniper, Skript, MVdWPlaceholderAPI, Vault, Multiverse-Core, PermissionsEx, ViaVersion, FeatherBoard, WildSkript, SkQuery, FastAsyncWorldEdit, ProtocolLib, CleanroomGenerator, Essentials, AnimatedNames, ExtrasSK, WorldEdit, LiteBans, DeluxeChat, BattleLevels, ServerListPlus, WorldGuard_

Thanks!

EDIT: My server is running java 7 apparently, sorry for wasting your time

**Comment by tim740** [comment]
Contact me on discord `tim740#1139`
