### ISSUE TITLE
Suggestion: CPU Expressions

### ISSUE THREAD

**Issue by Blueyescat** [tim740/skUtilities#20]
CPU Expressions

**Comment by tim740** [comment]
Some examples please

**Comment by Blueyescat** [comment]
`used C[entral]P[rocessing]U[nit]`
(percentage)

`speed of C[entral]P[rocessing]U[nit]`
`C[entralP[rocessing]U[nit]['[s]] speed)`
(X GHz)

`[total] C[entral]P[rocessing]U[nit] time`
(timespan)

`(available|number of) processor[s]`
`processor[s]'[s] number`
(number)

...
PROCESSOR_IDENTIFIER
PROCESSOR_ARCHITECTURE
PROCESSOR_ARCHITEW6432

**Comment by tim740** [comment]
Already in an addon

**Comment by Blueyescat** [comment]
it isn't
