### ISSUE TITLE
Suggestion: Base64 image encoding

### ISSUE THREAD

**Issue by abandonedaccount6235** [tim740/skUtilities#24]
```
base[ ]64 form of %string%
%string%['][s] base[ ]64 form
```
where the string is a path
```
set {_base64} to base64 form of "icons/main.png"
```

**Comment by Snow-Pyon** [comment]
it would be cool also if it accepts image URLs.

**Comment by tim740** [comment]
What uses could this have?

**Comment by Snow-Pyon** [comment]
base64 images are used for stuff such as skins (of players and player heads), MOTD icon and maps, so this would be pretty cool to have. This would also let us send base64 encoded images to websites (with Reqn) and that stuff.

**Comment by tim740** [comment]
Okay i see, ill add it next update :) (Which could be soon, not making any promises)
