### ISSUE TITLE
Can't get the name of the day

### ISSUE THREAD

**Issue by MrCrazyKill** [tim740/skUtilities#26]
Hello, I have an error when I execute this command:
`command /test:`
`    trigger:`
`        send "%day name from date now%`
Error: `ERROR [skUtilities] v0.9.0: Text '13/06/2017, 17:58' could not be parsed at index 8 (ExprDateInner.class)`

**Comment by tim740** [comment]
Still an issue?

**Comment by tim740** [comment]
Comment/reopen if this is still an issue

**Comment by tim740** [comment]
Comment/reopen if this is still an issue
