### ISSUE TITLE
ZipFile Error

### ISSUE THREAD

**Issue by itsrenderman** [tim740/skUtilities#29]
[skUtilities] v0.9.0: ZipFile: 'maps/********/*******.zip' doesn't exist, or doesn't have write permission! (EffUnzip.class)

(I had to block out name)
But it keeps saying that. I don't know why and I've also checked and the zipfile is 100% there in the maps folder on the server. Please help if you can.

**Comment by tim740** [comment]
i need more infomation, the path and the code you used if you don't want to show this publicly you can message me on discord `tim740#1139`
