### ISSUE TITLE
Can't seem to convert large integers to hexadecimal

### ISSUE THREAD

**Issue by Orendigo** [tim740/skUtilities#30]
Attempting to convert a large integer (like the UUID Least or UUID Most nbt tags) into hexadecimal returns the incorrect conversion output.

Testing code:

```
function entityUUID(e: entity) :: text:
    set {_uuidLeast} to convert num ("%tag ""UUIDLeast"" of nbt of {_e}%" parsed as integer) to hexa
    set {_uuidMost} to convert num ("%tag ""UUIDMost"" of nbt of {_e}%" parsed as integer) to hexa
    return "%{_uuidMost}% |-| %{_uuidLeast}%"
```

It seems like the expression will only return values of 8 digits in length.

**Comment by Syst3ms** [comment]
You can always try to convert it manually, but that's a bit hard I guess.

**Comment by tim740** [comment]
https://github.com/tim740/skUtilities/blob/master/src/uk/tim740/skUtilities/convert/ExprNumToHexa.java#L20
