### ISSUE TITLE
error with if yaml exist

### ISSUE THREAD

**Issue by DevonPalma** [tim740/skUtilities#31]
Code:
`command /test:
    trigger:
        if yaml path "machines.advanced_crafter" in file "{@file}" exist:
            message "test"`
errors:

> can't understand this condition: 'yaml path "machines.advanced_crafter" in file "plugins/LearnTheWorld/test.yml" exist' (crafting.sk, line 126: if yaml path "machines.advanced_crafter" in file "{@file}" exist:')

versions:  addon; 0.9.0 skript: dev29 minecraft: 1.12.1 java: build 1.8.0_131-b11

**Comment by Blueyescat** [comment]
```
y[a]ml[ path] %string% in file %-string% exists

y[a]ml[ path] %string% in file %-string% does(n't| not) exist
```
