### ISSUE TITLE
Suggestion: Parse Skript Code Effect

### ISSUE THREAD

**Issue by Blueyescat** [tim740/skUtilities#33]
Parses a Skript code, but doesn't execute the code.
```vb
parse s(c|k)ript [code] %strings% [logging] in %objects%
```
### Description
The `[logging] in %objects%` part only supports a list variable. Errors and/or warnings while parsing Skript code go to this list variable by order.

### Example
```vb
parse skript code "on join:" and "    send ""Welcome!""" logging in {_logs::*}

# {_logs::*} is not set here
```

**Comment by tim740** [comment]
Doesn't really fit
