### ISSUE TITLE
Can't properly delete a file

### ISSUE THREAD

**Issue by kumakuma215** [tim740/skUtilities#39]
Version : git-Paper-1062
Skript's Version : 2.2-dev33 by bensku
SkUtilities' version: 0.8.9

So, it's an annoying bug.
When I delete a file with SkUtilities, it deletes it. But not properly, I have to restart the server to delete it properly.

Explanations:
I create the file "A"
Then, I delete the file "A"
And, I try to recreate the file "A" with the same name, but it doesn't work. The file reappers in my folders, but if I try to access it, Notepad++ tells me it doesn't exist. If I try to delete it manually, it says I doesn't have the administrator's permission. And, obviously, the file doesn't work.

Could you please fix this? Thanks!

PS: Sorry for my poor English, I'm not English :/

**Comment by tim740** [comment]
Hmm ill have to look into this, also your running an old build of my addon https://github.com/tim740/skUtilities/releases/tag/v0.9.0
