### ISSUE TITLE
don't work on mc 1.12.2 Server

### ISSUE THREAD

**Issue by cknost** [tim740/skUtilities#43]
Hello,
I can't use this plugin in 1.12.2

**Comment by Olyno** [comment]
Error(s) in the console? Version of Skript? You say nothing about your problem except "I can't use this plugin in 1.12.2". We can't help you if you say not more informations 🤷‍♂️

**Comment by cknost** [comment]
Hi,
skript says that the plugin isn't installed. 
I can't use "on any move"

**Comment by Olyno** [comment]
If skript said you that the plugin isn't installed, it will not work. Take the [last version of skript](https://github.com/bensku/Skript/releases/download/dev34/Skript.jar)

**Comment by tim740** [comment]
`on any move` isn't part of this addon, this addon doesn't relie on a certain server version and next time please follow this as a guild for posting issues https://github.com/tim740/skUtilities/blob/master/CONTRIBUTING.md
