### ISSUE TITLE
Looking for some help.

### ISSUE THREAD

**Issue by ImLunaUwU** [tim740/skUtilities#50]
Hey there, i am trying to make a command start a .bat script on my server, but i keep getting errors, and i am suspecting it's because i don't really understand how it works yet, since when ever i try something else, still from this addon, it works fine. If somebody can help me do the last line or two correctly, i would be thankful :)

This is how the base of my script looks. 

> command /annoymajor:
>     description: Annoy Major, by sending him an alert, notifying you either need him, or just want to annoy!
>     usage: /annoymajor
>     permission: annoy.use
>     permission message: &cYou are not allowed to annoy Major&4!
>     executable by: players

**Comment by will2022** [comment]
You've not made any skript?
