### ISSUE TITLE
Why does skUtilities delete my yaml comments?

### ISSUE THREAD

**Issue by ImNotStable** [tim740/skUtilities#54]
#Comment
List:

_Becomes_

List:
  one: test

_After using this_

command /testyml:
    trigger:
        set yaml value "List.one" of file "plugins/Skript/test.yml" to "test"

_Question is in the title_

**Comment by kotazzz** [comment]
This is because the file is first completely parsed and converted to a "managed" format, and then the text is converted back. At the first stage, the comments are not saved in any way and when returning to the text format, the information about the comments is lost

**Comment by ImNotStable** [comment]
If only you were there a year ago lmao
