### ISSUE TITLE
URI Authority

### ISSUE THREAD

**Issue by Grimmy347** [tim740/skUtilities#6]
I am trying to do the command:
zip directory "/" to zip "/backup.zip" 
to backup my entire game folder but get the following error:
java.lang.IllegalArgumentException: URI has an authority component
     at sun.nio.fs.UnixUriUtils.fromUri(Unknown Source)
     at sun.nio.fs.UnixFileSystemProvider.getPath(Unknown Source)
     at java.nio.file.Paths.get(Unknown Source)

Thanks!

**Comment by tim740** [comment]
do you have discord? if so message me on their: 
Skript Chat Discord: https://discord.gg/V4qFVnh (Different from skUnity's Discord)
@tim740#1139

**Comment by tim740** [comment]
do you have discord? if so message me on their: 
Skript Chat Discord: https://discord.gg/0lx4QhQvwelCZbEX (Different from skUnity's Discord)
@tim740#1139

**Comment by tim740** [comment]
whats directory `/`?
if you want to zip the minecraft server root directory just do "" if you want to zip plugins do "plugins"

**Comment by tim740** [comment]
This is probably the reason your getting that error

**Comment by Grimmy347** [comment]
Well it works on my home server but on my remote server it gives the same error.

**Comment by Grimmy347** [comment]
doing:
command /backupzip:
	trigger:
		zip directory "" to zip "test.zip"

**Comment by Grimmy347** [comment]
I finally got discord to work
